### PR TITLE
Updated sqlalchemy>2.0

### LINKED ISSUE #155: Upgrade to sqlalchemy>2.0
## Detailed Description
This can be done using https://github.com/openclimatefix/pv-site-datamodel/issues/88
and pv-site-datamodel==1.0.17

## Context
- sqlalmacy upgrades should make things faster

## Possible Implementation
upgrade requirements and run tests

### PR DESCRIPTION
**Pull request by rahul-maurya11b**
# Pull Request

## Description

updated the sqlachemy >2.0 .
by doing the pvsite-model to version 1.0.17 . The lint and format test were giving error so added the dependency of pvsite-model geopandas = "^0.14.2" in pyproject.toml and  all test passes.

Fixes #155 

## How Has This Been Tested?

manually running pytest

- [ ] Yes

_If your changes affect data processing, have you plotted any changes? i.e. have you done a quick sanity check?_

- [ ] Yes

## Checklist:

- [x] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by rahul-maurya11b** [comment]
sir, do I have to create a PR that aligns with current commits because this commit shows changes of removed warnings that were merged externally?

**Comment by rahul-maurya11b** [comment]
@peterdudfield  sir please review  this one also.

**Comment by rahul-maurya11b** [comment]
@peterdudfield sir i have updated the branch which triggered the CI and test passes.

**Review by peterdudfield — APPROVED** [review]

**Comment by peterdudfield** [comment]
Amazing, thank you for doing this @rahul-maurya11b

**Comment by peterdudfield** [comment]
@all-contributors please add @rahul-maurya11b  for code

**Pull request merged**
