### PR TITLE
added a more timezone aware method for datetime utc

### PR DESCRIPTION
**Pull request by aryanbhosale**
# Pull Request

## Description

the datetime.utcnow() method is considered deprecated in modern Python versions, and it's recommended to use the more explicit datetime.now(tz=datetime.timezone.utc) instead. The utcnow() method is still functional, but it's considered less clear and less timezone-aware than the alternative. I have thus replaced the deprecated method with the newer one

Fixes #

Replaces the deprecated method with the newer one

## Checklist:

- [x] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [x] I have performed a self-review of my own code
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by aryanbhosale** [comment]
Hi @peterdudfield , could you please review this?

**Comment by peterdudfield** [comment]
Di you know why in this PR the code changes dont highlight the single lines changed? The whole file is changed. 

p.s run `make format` to fix linting erros

**Comment by aryanbhosale** [comment]
> Di you know why in this PR the code changes dont highlight the single lines changed? The whole file is changed.
> 
> p.s run `make format` to fix linting erros

it says that the makefile cant be found, and ive only changed the lines with utc, should i reopen a pr?

**Comment by aryanbhosale** [comment]
> > Di you know why in this PR the code changes dont highlight the single lines changed? The whole file is changed.
> > p.s run `make format` to fix linting erros
> 
> it says that the makefile cant be found, and ive only changed the lines with utc, should i reopen a pr?

In fact in my latest commit I've copy pasted the entire code from the original main repo and only made my changes to the specific lines, it still shows everything as changed

**Comment by peterdudfield** [comment]
> > > Di you know why in this PR the code changes dont highlight the single lines changed? The whole file is changed.
> > > p.s run `make format` to fix linting erros
> > 
> > 
> > it says that the makefile cant be found, and ive only changed the lines with utc, should i reopen a pr?
> 
> In fact in my latest commit I've copy pasted the entire code from the original main repo and only made my changes to the specific lines, it still shows everything as changed

weird, ive never seen that before.

lint still failing by the way.

**Pull request closed without merging**
