### PR TITLE
Added mechanism to log API requests 

### LINKED ISSUE #154: Save API requests
## Detailed Description
It would be good to save the api request and the username when each API call is made, and save it to a database

## Context
- similar to https://github.com/openclimatefix/uk-pv-national-gsp-api/blob/main/src/cache.py#L82

## Possible Implementation
In the cache function, add made in this issue - https://github.com/openclimatefix/pv-site-datamodel/issues/112
- add a test to check this value is written to the database

### PR DESCRIPTION
**Pull request by suleman1412**
# Pull Request

## Description
Implemented saving API calls for user.
Updated pvsite-datamodel to 1.0.19, sqlalchemy to 2.0 and geopandas to 0.14.2 as it caused a dependency issue  

Fixes #154 

## How Has This Been Tested?

pytest ran successfully locally

- [x] Yes

_If your changes affect data processing, have you plotted any changes? i.e. have you done a quick sanity check?_

- [ ] Yes

## Checklist:

- [x] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by suleman1412** [comment]
@peterdudfield does this work as expected?

**Comment by peterdudfield** [comment]
Could you add a test to check it works?

**Comment by peterdudfield** [comment]
> Could you add a test to check it works?

Or perhaps I can add a new issue to add tests for this, and then we can get this merge

**Comment by peterdudfield** [comment]
I had ot run `poetry lock --no-update` to update the poetry files, which makes everything work nicely now

**Comment by peterdudfield** [comment]
@all-contributors please add @suleman1412  for code

**Pull request merged**
